### ISSUE TITLE
Uncaught TypeError: Cannot read property 'assets' of undefined

### ISSUE THREAD

**Issue by yueling-juri** [bmoren/p5js-toolbar#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: [p5js-toolbar](https://github.com/bmoren/p5js-toolbar) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'assets' of undefined

```
At /Users/juri/.atom/packages/p5js-toolbar/lib/p5js-toolbar-view.js:159

TypeError: Cannot read property 'assets' of undefined
    at Request._callback (/packages/p5js-toolbar/lib/p5js-toolbar-view.js:159:28)
    at Request.self.callback (/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at /app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at /app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
p5js-snippets 0.4.4 
p5js-toolbar 0.2.1 
```

**Comment by bmoren** [comment]
can you tell me when this popped up? at program launch? were you connected to the web at the time? can you tell me what happens if you go to this URL in your browser: https://api.github.com/repos/processing/p5.js/releases

**Comment by yueling-juri** [comment]
Hi!
Yes, the crash happened when the program launch, since I just installed the latest version yesterday. I was connected to the web at that time.
Once I click the website I had a lot codes :

[
  {
    "url": "https://api.github.com/repos/processing/p5.js/releases/20694418",
    "assets_url": "https://api.github.com/repos/processing/p5.js/releases/20694418/assets",
    "upload_url": "https://uploads.github.com/repos/processing/p5.js/releases/20694418/assets{?name,label}",
    "html_url": "https://github.com/processing/p5.js/releases/tag/0.10.2",
    "id": 20694418,
    "node_id": "MDc6UmVsZWFzZTIwNjk0NDE4",
    "tag_name": "0.10.2",
    "target_commitish": "master",
    "name": "0.10.2",
    "draft": false,
    "author": {
      "login": "lmccart",
      "id": 191056,
      "node_id": "MDQ6VXNlcjE5MTA1Ng==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/191056?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lmccart",
      "html_url": "https://github.com/lmccart",
      "followers_url": "https://api.github.com/users/lmccart/followers",
      "following_url": "https://api.github.com/users/lmccart/following{/other_user}",
      "gists_url": "https://api.github.com/users/lmccart/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lmccart/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lmccart/subscriptions",
      "organizations_url": "https://api.github.com/users/lmccart/orgs",
      "repos_url": "https://api.github.com/users/lmccart/repos",
      "events_url": "https://api.github.com/users/lmccart/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lmccart/received_events",
      "type": "User",
      "site_admin": false
    },
    "prerelease": false,
    "created_at": "2019-10-14T21:57:33Z",
    "published_at": "2019-10-14T22:02:52Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/processing/p5.js/releases/assets/15478466",
        "id": 15478466,
        "node_id": "MDEyOlJlbGVhc2VBc3NldDE1NDc4NDY2",
        "name": "p5.js",
        "label": null,
        "uploader": {
          "login": "lmccart",
          "id": 191056,
          "node_id": "MDQ6VXNlcjE5MTA1Ng==",
          "avatar_url": "https://avatars3.githubusercontent.com/u/191056?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/lmccart",
          "html_url": "https://github.com/lmccart",
          "followers_url": "https://api.github.com/users/lmccart/followers",
          "following_url": "https://api.github.com/users/lmccart/following{/other_user}",
          "gists_url": "https://api.github.com/users/lmccart/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/lmccart/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/lmccart/subscriptions",
          "organizations_url": "https://api.github.com/users/lmccart/orgs",
          "repos_url": "https://api.github.com/users/lmccart/repos",
          "events_url": "https://api.github.com/users/lmccart/events{/privacy}",
          "received_events_url": "https://api.github.com/users/lmccart/received_events",
          "type": "User",
          "site_admin": false
        },

Something like these.

发件人: Ben Moren <notifications@github.com>
答复: bmoren/p5js-toolbar <reply@reply.github.com>
日期: 2019年10月23日 星期三 15:34
收件人: bmoren/p5js-toolbar <p5js-toolbar@noreply.github.com>
抄送: yueling-juri <yueling1022@gmail.com>, Author <author@noreply.github.com>
主题: Re: [bmoren/p5js-toolbar] Uncaught TypeError: Cannot read property 'assets' of undefined (#12)


can you tell me when this popped up? at program launch? were you connected to the web at the time? can you tell me what happens if you go to this URL in your browser: https://api.github.com/repos/processing/p5.js/releases

―

**Comment by bmoren** [comment]
great thanks, is it still popping up at all? or did it only happen just one time?
