### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by liquidzym** [bmoren/p5js-toolbar#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [p5js-toolbar](https://github.com/bmoren/p5js-toolbar) package 0.2.1

### Stack Trace

Uncaught SyntaxError: Unexpected token u in JSON at position 0

```
At file:///C:/Users/liquid/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/packages/p5js-toolbar/lib/p5js-toolbar-view.js:155:22)
    at self.callback (/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/app.asar/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-p5ref 0.4.0 
p5js-snippets 0.4.4 
p5js-toolbar 0.2.1 
p5play-snippets 0.7.0 
```

**Comment by bmoren** [comment]
can you please let me know what you were doing when this error was thrown?

**Comment by liquidzym** [comment]
sorry for the confusing,above error message its generated by atom.  
open up the atom ide it will pop up this message instantly
![issue](https://user-images.githubusercontent.com/51957/77717529-b3ba9980-701b-11ea-8e67-f1bdcb67c2a2.png)

**Comment by bmoren** [comment]
does this always pop up for you when you open atom? does it open when you you open atom with a project or with noting open?

can you try toggling off your packages (except the toolbar) and then turn them on one by one and see when the error gets thrown?

I have all the same packages you have installed except p5ref and playsnippets, so my suspicion is that there could be a conflict there?
