### ISSUE TITLE
Uncaught TypeError: _this.p5jsToolbarView.newProject is not a function

### ISSUE THREAD

**Issue by eeshannarula** [bmoren/p5js-toolbar#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [p5js-toolbar](https://github.com/bmoren/p5js-toolbar) package 0.1.5

### Stack Trace

Uncaught TypeError: _this.p5jsToolbarView.newProject is not a function

```
At C:\Users\abc\.atom\packages\p5js-toolbar\lib\p5js-toolbar.js:34

TypeError: _this.p5jsToolbarView.newProject is not a function
    at HTMLElement.p5jsToolbarNewProject (/packages/p5js-toolbar/lib/p5js-toolbar.js:34:62)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:42.1.0 open-on-github:repository (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:31.3.0 github:toggle-git-tab-focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:22 github:toggle-git-tab (atom-pane.pane)
     -7:10.2.0 github:toggle-github-tab (atom-pane.pane)
 26x -6:14.1.0 github:toggle-github-tab-focus (ul.list-inline.tab-bar.inset-panel)
     -3:49.2.0 core:confirm (input.hidden-input)
  2x -2:47.4.0 core:backspace (input.hidden-input)
     -2:43.3.0 core:confirm (input.hidden-input)
     -1:58.8.0 p5js-snippets:ref (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:17.5.0 open-on-github:repository (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:50.5.0 p5js-toolbar:run (atom-pane.pane)
     -0:37.5.0 p5js-toolbar:new-project (atom-pane.pane)
```

### Non-Core Packages

```
p5js-snippets 0.4.1 
p5js-toolbar 0.1.5 
```

**Comment by bmoren** [comment]
Thank you! working on this for the next release

**Comment by bmoren** [comment]
@iosonosempreio  this should be fixed now, please let me know if its working for you and if you run into any other issues!
